add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[❤](bold 211)"
error_symbol = "[❤](bold 161)"

[username]
show_always = true
style_user = "bold 5"
format = "[$user]($style) "

[directory]
style = "bold #cba6f7"
truncation_length = 3
truncation_symbol = ".../"
format = "[$path]($style) "
fish_style_pwd_dir_length = 1

[jobs]
style = "bold 211"

[cmd_duration]
disabled = true

[lua]
disabled = true

[package]
disabled = true

[nodejs]
disabled = true
